---

.destroy:env:
  stage: 'build'
  allow_failure: true
  extends:
    - '.k8s:init'
  variables:
    message: "destroy feature env"
  before_script:
    - !reference [.k8s:init, before_script]
    - 'git clone "$FEATURE_REPO" features'
  script:
    - |
      merged=$(curl -s --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
        "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests?state=merged&order_by=updated_at&sort=desc&per_page=1" \
        | jq -r '.[0].source_branch' |  tr '[:upper:]' '[:lower:]' | grep -o -E 'kan-[0-9]+' | tr '\n' ' ' | sed 's/ //g' | sort -u) || true
    - 'cd features'
    - 'git pull --rebase origin main'
    - 'echo "Merged branches: $merged"'
    - |
      if [[ "${merged}" != "" ]]; then
        echo "Remove Feature ENV: ${merged}"
        aws s3 rm s3://${S3_BUCKET}/${merged} --recursive
        rm -rf ${merged}-* || true
        rm -rf destroyed/${merged}-* || true
        curl -k "https://junction.service.int/api/v1/environments/names/$(echo ${merged} | sed 's/ //g')" \
        -X 'DELETE' \
        -H 'Accept: */*' \
        -H 'Connection: keep-alive' \
        -H 'Content-Type: application/json' || true
      fi
    - message="destroy feature envs ${merged}"
    - !reference ['.git:commit', after_script]
